# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-jessie64"

  # Forwarded port mappings
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  
  # Private network
  config.vm.network "private_network", ip: "10.0.0.2"

  # Share an additional folder to the guest VM
  config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration for Virtualbox
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  # Provisioning script
  config.vm.provision "shell", inline: <<-SHELL
    # Packages available from default repositories
    apt-get update
    apt-get install -y apt-transport-https ca-certificates software-properties-common
    apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual linux-headers-amd64
    apt-get install -y sudo vim git curl wget rsync
    apt-get install -y gcc g++ make python python3 pylint ruby
    apt-get install -y xserver-xorg xinit i3 feh lxterminal
    apt-get install -y virtualbox-guest-utils virtualbox-guest-dkms virtualbox-guest-x11
    
    # Install /etc/skel config and also new sources.list.d entries, including Docker repository
    cd /var/tmp && git clone https://github.com/skrytt/devenv && cd devenv
    for dir in /etc/apt/sources.list.d /etc/skel/.i3 /etc/skel/.config/lxterminal
    do
      mkdir -p ${dir}
    done
    for file in /etc/skel/.vimrc /etc/skel/.xinitrc \
    /etc/skel/.config/lxterminal/lxterminal.conf /etc/skel/.i3/config
    do
      cp {.,}${file}
    done
    rm -rf /var/tmp/devenv

    # Docker 
    # See: https://docs.docker.com/engine/installation/linux/debian/
    curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add -
    apt-key fingerprint 58118E89F3A912897C070ADBF76221572C52609D
    add-apt-repository \
       "deb https://apt.dockerproject.org/repo/ \
       debian-$(lsb_release -cs) \
       main"
    apt-get update
    apt-get -y install docker-engine

    # User config    
    useradd -m -U -s/bin/bash mkemp
    
    # Install pathogen for mkemp
    mkdir -p /home/mkemp/.vim/autoload /home/mkemp/.vim/bundle && curl -LSso /home/mkemp/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
    # Install syntastic for mkemp
    cd /home/mkemp/.vim/bundle && git clone --depth=1 https://github.com/vim-syntastic/syntastic.git
    # Fix permissions
    chown -R mkemp:mkemp /home/mkemp
    
    # Give mkemp sudo permissions
    bash -c 'echo "mkemp ALL=(ALL:ALL) ALL" | (EDITOR="tee -a" visudo)'
    
    # mkemp's password will need to be set manually by 'vagrant' user using: 'passwd mkemp'
    
  SHELL
end
