# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fujimakishouten/debian-stretch64"

  # Forwarded port mappings
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Private network
  config.vm.network "private_network", ip: "10.0.0.2"

  # Shared data folder folder to the guest VM
  config.vm.synced_folder "D:/vboxshare", "/mnt/vboxshare"

  # Provider-specific configuration for Virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end

  # Workaround for TTY errors
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # Provisioning script
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/skrytt/devenv/master/scripts/provision.sh"
end
