# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fujimakishouten/debian-stretch64"

  # Forwarded port mappings
  config.vm.network "forwarded_port", guest: 80, host: 8080
  
  # Private network
  config.vm.network "private_network", ip: "10.0.0.2"

  # Shared data folder folder to the guest VM
  config.vm.synced_folder "D:/vboxshare", "/mnt/vboxshare"
  
  # Provider-specific configuration for Virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end
  
  # Workaround for TTY errors
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # Provisioning script
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt update
    apt upgrade -y
    # Some packages we need for grabbing data from the net and for supporting https transport for apt
    apt install -y git apt-transport-https ca-certificates software-properties-common curl

    # Wipe existing apt repository configuration
    rm -f /etc/apt/sources.list
    rm -f /etc/apt/sources.list.d/*

    # Grab files from github, including new sources.list.d entries. Install them to /etc/.
    # If user mkemp already exists (e.g. if this is a reprovision) then copy the files to home too.
    test -d "/var/tmp/devenv" || git clone https://github.com/skrytt/devenv /var/tmp/devenv
    cd /var/tmp/devenv
    chown -R root:root ./etc && rsync -a {.,}/etc/
    chown -R mkemp:mkemp ./etc && rsync -a ./etc/skel/ /home/mkemp/
    rm -rf /var/tmp/devenv

    # Get Docker repository key, fingerprint and add repo
    # See: https://docs.docker.com/engine/installation/linux/debian/
    curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add -
    apt-key fingerprint 58118E89F3A912897C070ADBF76221572C52609D
    add-apt-repository \
       "deb https://apt.dockerproject.org/repo/ \
       debian-$(lsb_release -cs) \
       main"

    # Continue installing
    apt update
    apt install -y linux-image-$(uname -r) linux-headers-amd64 \
        vim wget rsync gcc g++ make automake python python3 pylint ruby xserver-xorg xinit \
        i3 feh lxterminal docker-engine

    # User config and updating of home config
    test -d "/home/mkemp" || useradd -m -U -s/bin/bash mkemp
    # Symlink to the vboxshare dir
    test -e /home/mkemp/vboxshare || ln -s /home/mkemp/vboxshare /mnt/vboxshare
    
    # Install plugins for vim
    # Install pathogen for mkemp
    mkdir -p /home/mkemp/.vim/autoload /home/mkemp/.vim/bundle && curl -LSso /home/mkemp/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
    # Install syntastic for mkemp
    cd /home/mkemp/.vim/bundle && git clone --depth=1 https://github.com/vim-syntastic/syntastic.git
    # Install solarized colourscheme for mkemp
    cd /home/mkemp/.vim/bundle && git clone https://github.com/altercation/vim-colors-solarized.git
    # Fix permissions for vim plugins
    chown -R mkemp:mkemp /home/mkemp/.vim

    # Give mkemp sudo permissions
    bash -c 'echo "mkemp ALL=(ALL:ALL) ALL" | (EDITOR="tee -a" visudo)'

    # mkemp's password will need to be set manually by 'vagrant' user using: 'passwd mkemp'.
    # A manual re-installation of VirtualBox Guest Additions is then recommended using an up-to-date guest additions ISO.

  SHELL
end
